'use strict';
const mobile=document.body.dataset.mobile==='true';
const view=document.body.dataset.view||'home';
const names=['HOME','ETF 상세분석','보유종목 관리','종목간 비교분석'];
const routes=['index.html','detail.html','holdings.html','compare.html'];
const keys=['home','detail','holdings','compare'];
const funds=[
 {code:'458730',name:'TIGER 미국배당다우존스',units:'581',avg:'9,850',current:'11,020',rate:'+15.70%',profit:'+898,410',unreal:'+679,770',value:'6,402,620',capital:'5,722,850',div:'218,640',weight:'48.15%',color:'#fbbf24'},
 {code:'441640',name:'KODEX 미국배당커버드콜',units:'325',avg:'11,500',current:'12,090',rate:'+9.55%',profit:'+357,050',unreal:'+191,750',value:'3,929,250',capital:'3,737,500',div:'165,300',weight:'31.45%',color:'#60a5fa'},
 {code:'497880',name:'SOL CD금리&머니마켓',units:'2,400',avg:'1,010',current:'1,047',rate:'+7.87%',profit:'+190,860',unreal:'+88,800',value:'2,512,800',capital:'2,424,000',div:'102,060',weight:'20.40%',color:'#10b981'}
];
const icon=(n)=>{const paths={home:'M3 10l9-7 9 7v11h-6v-7H9v7H3z',detail:'M3 18V8m6 10V4m6 14v-8m6 8V6',holdings:'M3 7h18v14H3zM7 7V3h10v4',compare:'M4 20V9m8 11V4m8 16V12',review:'M5 3h14v18H5zM8 8h8M8 12h8M8 16h5',chevron:'M6 9l6 6 6-6',arrow:'M5 12h14m-6-6 6 6-6 6',plus:'M12 4v16M4 12h16',search:'M20 20l-5-5M16 9a7 7 0 1 1-14 0 7 7 0 0 1 14 0',bell:'M6 8a6 6 0 0 1 12 0v7l3 3H3l3-3zM10 21h4',settings:'M12 3v3m0 12v3M3 12h3m12 0h3M6 6l2 2m8 8 2 2M6 18l2-2m8-8 2-2M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',back:'M14 5l-7 7 7 7',check:'M5 12l4 4L19 6'};return `<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[n]||paths.detail}"/></svg>`;};
const sample='';
const metric=(label,value,sub='',cls='')=>`<div class="metric"><span>${label}</span><strong class="${cls}">${value}</strong>${sub?`<small>${sub}</small>`:''}</div>`;
function chart(mode='line',normalized=false){if(mode==='bars'){return `<svg class="chart" viewBox="0 0 760 170" role="img" aria-label="가상 월별 분배금 막대 그래프"><g stroke="#31465b"><path d="M35 35H730M35 80H730M35 125H730"/></g>${Array.from({length:20},(_,i)=>`<rect x="${42+i*34}" y="${96-(i%6)*7-i*1.8}" width="22" height="${50+(i%6)*7+i*1.8}" rx="3" fill="#60a5fa"/>`).join('')}<g fill="#a5b5c9" font-size="13"><text x="35" y="166">2025.03</text><text x="245" y="166">2025.09</text><text x="465" y="166">2026.03</text><text x="680" y="166">2026.09</text></g></svg>`;}
return `<svg class="chart ${normalized?'overlay':''}" viewBox="0 0 760 220" role="img" aria-label="${normalized?'100 시작 정규화':'NAV와 NAV-TR'} 가상 추이 그래프"><g stroke="#304254" stroke-width="1"><path d="M42 32H730M42 82H730M42 132H730M42 182H730"/><path d="M42 25V188M215 25V188M386 25V188M558 25V188M730 25V188"/></g><g fill="#a5b5c9" font-size="13"><text x="8" y="36">160</text><text x="8" y="86">140</text><text x="8" y="136">120</text><text x="8" y="186">100</text><text x="42" y="213">2023.09</text><text x="225" y="213">2024.09</text><text x="470" y="213">2025.09</text><text x="674" y="213">2026.09</text></g><path data-line="nav" d="M42 177L73 169 96 172 120 155 144 162 166 146 190 150 218 134 245 143 277 138 310 151 340 133 375 140 410 120 443 134 478 111 500 135 524 128 550 143 583 137 615 119 646 127 676 108 704 117 730 100" fill="none" stroke="#60a5fa" stroke-width="3"/><path data-line="tr" d="M42 177L73 163 96 163 120 145 144 150 166 130 190 133 218 113 245 117 277 105 310 115 340 94 375 101 410 78 443 87 478 62 500 91 524 77 550 88 583 63 615 53 646 58 676 38 704 45 730 27" fill="none" stroke="#10b981" stroke-width="3"/>${normalized?'<path data-line="third" d="M42 177L73 171 120 165 166 154 218 148 277 144 340 132 410 118 478 109 550 90 615 79 676 55 730 40" fill="none" stroke="#fb7185" stroke-width="3"/>':''}</svg>`;}
function pcShell(content){return `<aside class="sidebar"><a class="brand" href="index.html"><span class="brand-mark">${icon('detail')}</span><span><small>돈냄새연구소의</small><b>월배당 ETF 바이블</b></span></a><nav>${keys.map((k,i)=>`<a class="side-link ${k===view?'active':''}" href="${routes[i]}">${icon(k)}${names[i]}</a>`).join('')}<button class="side-link" data-placeholder="리포트 / 리뷰">${icon('review')}리포트 / 리뷰 <small>예정</small></button></nav><div class="side-copy">선택 → 운용 → 리뷰<br><span>정보는 연결하고,<br>우리는 분석합니다.</span></div><a class="device-link" href="mobile-holdings.html">내 투자 주머니 · 모바일 ${icon('arrow')}</a></aside><div class="workspace"><header class="topbar"><nav>${keys.map((k,i)=>`<a href="${routes[i]}" class="${view===k?'active':''}">${names[i]}</a>`).join('')}</nav>${sample}</header><main>${content}</main><footer>돈냄새연구소의 월배당 ETF 바이블</footer></div>`;}
function home(){return `<section class="home-hero"><div class="hero-copy"><span class="eyebrow">돈냄새연구소의</span><h1>월배당 ETF 바이블</h1><h2><span>분배가 만드는</span><br>두 번째 월급</h2><p class="philosophy">얼마나 주는지가 아니라,<br>주고도 얼마나 남는지를 봅니다.</p><p class="muted">분배와 재투자, 그리고 남아 있는 원금.<br>돈의 흐름을 한눈에 확인하세요.</p><div class="flow"><span>선택</span>→<span>운용</span>→<span>리뷰</span></div></div><div class="coin-visual"><img src="assets/approved-home-coins.png" alt="분배·동전·잔존가치"></div></section><form class="search-bar" id="search-form"><input aria-label="종목명 또는 코드 검색" placeholder="종목명 또는 코드 입력 (예: 458730, TIGER 미국배당다우존스)"><button aria-label="상세분석 열기">${icon('search')}</button></form><section class="home-entries">${[['detail','분배금 너머의 진짜 성과','ETF 상세분석','분배·NAV·재투자 모델을 한 흐름으로'],['holdings','내가 산 뒤의 진짜 수익','보유종목 관리','받은 분배금과 실제 계좌 성과를 점검'],['compare','같은 조건에서 제대로 비교','종목간 비교분석','공통 기간과 기준으로 차이를 확인'],['review','내 투자 기록','리포트 / 리뷰','분석과 운용 기록을 보관']].map(([k,t,n,d])=>`<${k==='review'?'button':'a'} ${k==='review'?'data-placeholder="리포트 / 리뷰"':`href="${routes[keys.indexOf(k)]}"`} class="entry"><span class="entry-icon ${k}">${icon(k)}</span><div><small>${t}</small><h3>${n}</h3><p>${d}</p></div>${icon('arrow')}</${k==='review'?'button':'a'}>`).join('')}</section>`;}
const periods=(kind='detail')=>`<div class="periods" role="group" aria-label="공통 분석 기간">${['1년','3년','5년','전체','직접지정'].map((x,i)=>`<button data-period="${x}" class="${i===1?'active':''}" aria-pressed="${i===1}">${x}</button>`).join('')}</div><div class="custom-period" hidden><label>시작일<input type="date" value="2023-09-30"></label><label>종료일<input type="date" value="2026-09-30"></label><button data-apply-date>적용</button></div><p class="period-caption">3년 선택 · 샘플 수치는 기간 전환에 따라 재계산하지 않습니다.</p>`;
function section(id,title,content,number){return `<details class="panel section" id="${id}" open><summary><span class="section-number">${number}</span><h2>${title}</h2>${icon('chevron')}</summary><div class="section-body">${content}</div></details>`;}
function detail(){return renderRealDetail(null);}
function holdingDetail(f){return `<div class="holding-expanded"><div class="holding-meta"><h3>${f.name}</h3><span>${f.code} · 가상 계좌</span></div><div class="metrics four">${metric('평균매수가',f.avg+'원')}${metric('평가기준 NAV',f.current+'원')}${metric('수량',f.units+'좌')}${metric('최초매수일','2025.03.12')}</div><div class="metrics three">${metric('투자원금',f.capital+'원','비중 '+f.weight)}${metric('현재 평가액',f.value+'원')}${metric('평가손익 (NAV 기준)',f.unreal+'원','','positive')}${metric('실제 수령 분배금',f.div+'원','가상 계좌값')}${metric('분배 포함 실질손익',f.profit+'원','가상 계좌값','positive')}</div><div class="model-block"><b>NAV / NAV-TR 모델 점검</b><p>매수 이후 NAV +8.4% · NAV-TR +12.6% (가상)<br>Raw MDD −18.60% · NAV-TR MDD −12.10% · 전고점 회복 (가상)</p><small>계좌 손익과 세전 전액 재투자 모델은 별도 지표입니다.</small></div><div class="recent-change">최근 기간 변화 +1.2%p · 시장 TR 대비 −2.4%p (가상)</div><a class="outline" href="${mobile?'mobile-detail.html':'detail.html'}?code=${f.code}">상세분석 ${icon('arrow')}</a></div>`;}
function holdingCards(){return funds.map((f,i)=>`<details class="holding-card" ${i===0?'open':''} data-holding="${f.code}"><summary><span class="fund-mark" style="--fund:${f.color}">${i+1}</span><span class="fund-name"><small>${f.code}</small><strong>${f.name}</strong><span class="holding-mini">${f.units}좌 <i>${f.avg}원</i> ${f.current}원</span></span><span class="holding-result positive"><strong>${f.rate}</strong><small>(${f.profit}원)</small><span class="status">전고점 회복 · 가상</span></span>${icon('chevron')}</summary>${holdingDetail(f)}</details>`).join('');}
function holdings(){return `<header class="page-heading"><div><span class="eyebrow">운용 · 계속 점검</span><h1>내 투자 주머니</h1></div><button class="primary" data-add>${icon('plus')}종목 추가</button></header><div class="portfolio-summary"><div class="metrics three">${metric('총 투자원금','11,884,350원')}${metric('현재 평가금액','12,844,670원')}${metric('평가손익 (NAV 기준)','+960,320원','','positive')}</div><div class="metrics three">${metric('누적 실제 수령 분배금','486,000원','가상 계좌값')}${metric('분배 포함 실질손익','+1,446,320원','+12.17% · 가상 계좌값','positive')}${metric('원금회수율','4.09%','누적분배 / 투자원금')}</div></div><div class="filter-row">${['전체 (3)','수익중 (3)','손실중 (0)'].map((x,i)=>`<button data-filter="${i}" class="${i===0?'active':''}">${x}</button>`).join('')}<span class="muted">계좌 성과 · 모델 결과 별도 표시</span></div><div class="holdings-desktop"><div class="holding-list">${holdingCards()}</div><aside class="panel holdings-note"><h2>내가 산 뒤의 진짜 수익</h2><p>현재 평가손익과 받은 분배금을 함께 확인합니다.</p><div class="model-block"><b>실제 계좌 성과</b><p>평가손익 + 누적 실제 수령 분배금</p></div><div class="model-block"><b>NAV-TR 모델</b><p>세전 분배금 전액 재투자를 가정한 NAV 모델</p></div><p class="definition">이 화면의 모든 값은 가상값이며 실제 보유 내역을 저장하지 않습니다.</p><button class="outline" data-placeholder="월간 리뷰">월간 리뷰 ${icon('arrow')}</button></aside></div>`;}
function compare(){return `<header class="page-heading"><div><span class="eyebrow">선택 · 공통 조건 비교</span><h1>ETF 종목 비교</h1></div><button class="primary" data-select>${icon('plus')}종목 추가 · 2~5개</button></header><div class="compare-chips">${funds.map((f)=>`<button class="compare-chip selected" data-code="${f.code}" aria-pressed="true"><small>${f.code}</small><strong>${f.name}</strong><span>×</span></button>`).join('')}</div><div class="compare-tabs" role="tablist">${['수익률 비교','분배 비교','MDD 비교','기타 지표'].map((x,i)=>`<button role="tab" aria-selected="${i===0}" data-compare-tab="${i}" class="${i===0?'active':''}">${x}</button>`).join('')}</div><section class="panel compare-main"><div class="compare-toolbar"><h2 id="comparison-title">NAV vs NAV-TR · 100 시작</h2><div class="toggle">${['NAV','NAV-TR'].map((x,i)=>`<button data-model="${x}" class="${i===1?'active':''}" aria-pressed="${i===1}">${x}</button>`).join('')}</div></div>${periods('compare')}<div class="legend">${funds.map((f)=>`<span style="--dot:${f.color}">${f.code}</span>`).join('')}</div>${chart('line',true)}<p class="definition">같은 기간 · 100 시작 정규화 · 가상 모델 그래프</p></section><section class="panel"><h2 class="panel-title">핵심 지표 비교</h2><div class="table-scroll"><table><thead><tr><th>지표 · 3년 (가상)</th>${funds.map(f=>`<th data-col="${f.code}">${f.code}<small>${f.name}</small></th>`).join('')}</tr></thead><tbody>${[['NAV 변화','+16.2%','+9.4%','+8.1%'],['NAV-TR 변화','+22.7%','+35.1%','+7.8%'],['누적 분배 (1좌)','498원','840원','62원'],['Raw NAV MDD','−18.60%','−28.40%','−4.30%'],['NAV-TR MDD','−12.10%','−21.80%','−3.60%'],['회복기간','142일','220일','70일'],['구성종목 중복도','24% · 가상','24% · 가상','0% · 가상']].map(r=>`<tr><th>${r[0]}</th>${r.slice(1).map((v,i)=>`<td data-col="${funds[i].code}">${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section><section class="panel"><h2 class="panel-title">차원별 상대 강점 · 가상 데이터</h2><p>분배 규모, NAV-TR 변화, 최대 낙폭과 회복기간을 각각 비교합니다. 임의 종합점수나 투자 추천은 제공하지 않습니다.</p></section>`;}
function mobileNav(){return `<nav class="bottom-nav" aria-label="모바일 하단 내비게이션">${[['home','홈'],['detail','분석'],['holdings','보유'],['compare','비교'],['review','리뷰']].map(([k,t])=>`<${['detail','holdings','home'].includes(k)?'a':'button'} ${k==='detail'?'href="mobile-detail.html"':k==='home'?`data-home-code href="index.html?code=${encodeURIComponent(new URLSearchParams(location.search).get('code')||'')}"`:k==='holdings'?'href="mobile-holdings.html"':`data-mobile-placeholder="${t}"`} class="${((view===k&&new URLSearchParams(location.search).get('tab')!=='home')||k==='home'&&new URLSearchParams(location.search).get('tab')==='home')?'active':''}" ${view===k?'aria-current="page"':''}>${icon(k)}<span>${t}</span></${['detail','holdings','home'].includes(k)?'a':'button'}>`).join('')}</nav>`;}
function mobileShell(content){return `<div class="mobile-app"><header class="mobile-header"><div><small>돈냄새연구소의</small><b>월배당 ETF 바이블</b></div></header>${content}${mobileNav()}</div>`;}
function mobileHoldings(){return `<main class="mobile-content"><h1 class="pocket-title">내 투자 주머니</h1><section class="pocket-hero"><div class="mobile-periods">${['이번달','지난달','분기','전체'].map((x,i)=>`<button data-pocket-period="${x}" class="${i===0?'active':''}" aria-pressed="${i===0}">${x}</button>`).join('')}</div><span class="hero-label">분배 포함 실질손익</span><strong class="pocket-value positive">+1,446,320<small>원</small></strong><div class="pocket-rate positive">+12.17% <span>지난달 대비 +186,400원 · +1.5%p</span></div><div class="metrics four compact">${metric('투자원금','1,188.4만')}${metric('평가금액','1,284.5만')}${metric('누적분배','48.6만')}${metric('원금회수율','4.09%')}</div><div class="nav-profit">평가손익 (NAV 기준) <b class="positive">+960,320원</b></div><small class="muted" id="pocket-period-caption">이번달 · UI 검수용 가상 계좌값</small></section><div class="filter-row">${['전체 (3)','수익중 (3)','손실중 (0)'].map((x,i)=>`<button data-filter="${i}" class="${i===0?'active':''}">${x}</button>`).join('')}</div><section class="holding-list">${holdingCards()}</section><p class="definition">분배 포함 실질손익은 가상 계좌 성과입니다.<br>NAV-TR은 세전 전액 재투자 모델로 별도 표시합니다.</p><button class="primary mobile-add" data-add>${icon('plus')}종목 추가</button></main>`;}
function mobileDetail(){return `<main class="mobile-content detail-mobile"><a class="back-link" href="mobile-holdings.html">${icon('back')}내 투자 주머니</a>${detail()}</main>`;}
document.getElementById('app').innerHTML=mobile?mobileShell(view==='holdings'?mobileHoldings():mobileDetail()):pcShell(({home,detail,holdings,compare})[view]());
document.body.insertAdjacentHTML('beforeend',`<dialog id="ui-dialog"><button class="dialog-close" aria-label="닫기">×</button><h2 id="dialog-title"></h2><div id="dialog-content"></div><button class="primary dialog-done">확인</button></dialog><div id="toast" role="status" aria-live="polite"></div>`);
const dialog=document.getElementById('ui-dialog');
const toast=t=>{const e=document.getElementById('toast');e.textContent=t;e.classList.add('visible');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>e.classList.remove('visible'),3500);};
function showDialog(title,body){document.getElementById('dialog-title').textContent=title;document.getElementById('dialog-content').innerHTML=body;dialog.showModal();}
function activeGroup(button,selector){button.parentElement.querySelectorAll(selector).forEach(e=>{e.classList.toggle('active',e===button);if(e.hasAttribute('aria-pressed'))e.setAttribute('aria-pressed',String(e===button));if(e.hasAttribute('aria-selected'))e.setAttribute('aria-selected',String(e===button));});}
function updateComparison(){const selected=[...document.querySelectorAll('.compare-chip.selected')].map(e=>e.dataset.code);document.querySelectorAll('[data-col]').forEach(e=>e.hidden=!selected.includes(e.dataset.col));document.querySelectorAll('.compare-chip').forEach(e=>e.setAttribute('aria-pressed',String(e.classList.contains('selected'))));document.querySelectorAll('.overlay path[data-line]').forEach((e,i)=>{e.style.display=selected.includes(funds[i]?.code)?'':'none';});}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
if(b.matches('.dialog-close,.dialog-done')){dialog.close();document.querySelectorAll('.bottom-nav button').forEach(x=>x.classList.remove('active'));return;}
if(b.dataset.placeholder){showDialog(b.dataset.placeholder,'<p>이 영역은 후속 구현 범위입니다. 이번 UI Shell에서는 화면 위치와 이동 반응을 확인합니다.</p><p class="definition">실데이터 연결 및 실제 저장은 수행하지 않습니다.</p>');}
if(b.hasAttribute('data-mobile-placeholder')){document.querySelectorAll('.bottom-nav>*').forEach(x=>x.classList.remove('active'));b.classList.add('active');showDialog(b.dataset.mobilePlaceholder,'<p>모바일 '+b.dataset.mobilePlaceholder+' 화면은 후속 범위입니다.</p><p>현재 핵심 화면: 보유종목 관리 · ETF 상세분석</p>');}
if(b.hasAttribute('data-period')){activeGroup(b,'button');const p=b.closest('.section-body,.compare-main');p.querySelector('.custom-period').hidden=b.dataset.period!=='직접지정';p.querySelector('.period-caption').textContent=b.dataset.period+' 선택 · 샘플 수치는 재계산하지 않습니다.';}
if(b.hasAttribute('data-apply-date')){const p=b.closest('.section-body,.compare-main');const values=[...p.querySelectorAll('input[type=date]')].map(x=>x.value);if(!values[0]||!values[1]||values[0]>values[1]){toast('시작일과 종료일을 확인해 주세요.');return;}p.querySelector('.period-caption').textContent=values.join(' ~ ')+' · 가상값, 재계산 없음';toast('직접지정 기간의 UI 선택을 반영했습니다.');}
if(b.hasAttribute('data-section')){const target=document.getElementById(b.dataset.section);target.open=true;target.scrollIntoView({behavior:'smooth',block:'start'});activeGroup(b,'button');}
if(b.hasAttribute('data-pocket-period')){activeGroup(b,'button');document.getElementById('pocket-period-caption').textContent=b.dataset.pocketPeriod+' 선택 · 가상 계좌값, 재계산 없음';}
if(b.hasAttribute('data-filter')){activeGroup(b,'button');document.querySelectorAll('.holding-card').forEach(x=>x.hidden=b.dataset.filter==='2');document.querySelector('.empty-state')?.remove();if(b.dataset.filter==='2')document.querySelector('.holding-list').insertAdjacentHTML('beforeend','<div class="empty-state">가상 목록에 손실중인 종목이 없습니다.</div>');}
if(b.hasAttribute('data-add')){showDialog('내 보유종목에 추가',`<p>UI 검수용 추가 화면입니다. 실제 저장은 다음 단계에서 연결합니다.</p><label>종목<select><option>458730 · TIGER 미국배당다우존스 (샘플)</option><option>441640 · KODEX 미국배당커버드콜 (샘플)</option></select></label><div class="form-grid"><label>평균매수가<input type="number" min="1" value="9850"></label><label>수량<input type="number" min="1" value="120"></label></div><label>최초매수일<input type="date" value="2025-03-12"></label><button class="outline" data-demo-save>추가 시연</button>`);}
if(b.hasAttribute('data-demo-save')){const vals=[...dialog.querySelectorAll('input')];if(vals.some(x=>!x.value||!x.checkValidity())){toast('입력값을 확인해 주세요.');return;}dialog.close();toast('추가 동작 시연 완료 · 실제 보유 내역은 저장하지 않았습니다.');}
if(b.matches('.compare-chip')){const count=document.querySelectorAll('.compare-chip.selected').length;if(b.classList.contains('selected')&&count<=2){toast('비교 종목은 최소 2개를 선택해 주세요.');return;}b.classList.toggle('selected');updateComparison();}
if(b.hasAttribute('data-select')){showDialog('비교 종목 선택',funds.map(f=>`<label class="check-row"><input type="checkbox" value="${f.code}" ${document.querySelector(`[data-code="${f.code}"]`).classList.contains('selected')?'checked':''}>${f.code} · ${f.name}</label>`).join('')+'<p class="definition">가상 종목 3개 제공 · 2~5개 선택 규칙</p><button class="outline" data-apply-compare>선택 적용</button>');}
if(b.hasAttribute('data-apply-compare')){const codes=[...dialog.querySelectorAll('input:checked')].map(x=>x.value);if(codes.length<2||codes.length>5){toast('2~5개 종목을 선택해 주세요.');return;}document.querySelectorAll('.compare-chip').forEach(x=>x.classList.toggle('selected',codes.includes(x.dataset.code)));updateComparison();dialog.close();}
if(b.hasAttribute('data-compare-tab')){activeGroup(b,'button');const titles=['NAV vs NAV-TR · 100 시작','월별 분배 규모 비교 · 가상','최대 낙폭 비교 · 가상','구성종목 중복도 · 가상'];document.getElementById('comparison-title').textContent=titles[+b.dataset.compareTab];const svg=document.querySelector('.compare-main .chart');svg.classList.toggle('distribution-mode',b.dataset.compareTab==='1');toast(b.textContent+' 선택 · 하단 핵심 지표표에서 동일 조건으로 확인합니다.');}
if(b.hasAttribute('data-model')){activeGroup(b,'button');document.querySelector('.compare-main').dataset.model=b.dataset.model;document.getElementById('comparison-title').textContent=b.dataset.model+' · 100 시작 정규화 (가상)';const svg=document.querySelector('.compare-main .chart');svg.style.filter=b.dataset.model==='NAV'?'saturate(.6)':'';svg.querySelectorAll('path[data-line]').forEach(x=>x.setAttribute('transform',b.dataset.model==='NAV'?'translate(0 18) scale(1 .9)':''));}
});
document.getElementById('search-form')?.addEventListener('submit',e=>{e.preventDefault();const term=e.target.querySelector('input').value.trim();location.href='detail.html'+(term?'?q='+encodeURIComponent(term):'');});
document.querySelectorAll('.holding-card').forEach(d=>d.addEventListener('toggle',()=>{d.classList.toggle('selected',d.open);}));
const code=new URLSearchParams(location.search).get('code');if(code&&view==='detail'&&typeof renderRealDetail==='undefined'){const f=funds.find(x=>x.code===code);if(f){document.querySelector('.identity h1').textContent=f.name;document.querySelector('.identity small').textContent=f.code+' · 가상 종목 선택';document.querySelector('.strategy').textContent='선택한 종목의 헤더 이동 시연입니다. 아래 분석 수치는 공통 가상 템플릿이며 이 종목의 실제 결과가 아닙니다.';}}
