'use strict';
function copyText(el,text){for(const part of String(text||'').split(/(\*\*[^*]+\*\*|`[^`]+`)/g)){if(!part)continue;if(part.startsWith('**')){const strong=document.createElement('strong');strong.textContent=part.slice(2,-2);el.append(strong);}else el.append(document.createTextNode(part.startsWith('`')?part.slice(1,-1):part));}}
(async()=>{
 const response=await fetch('./data/term-help-content.json');if(!response.ok)return;const data=await response.json(),nav=document.querySelector('.terms-nav'),sections=document.querySelector('#terms-sections');
 const q=new URLSearchParams(location.search),from=['detail.html','mobile-detail.html'].includes(q.get('from'))?q.get('from'):'detail.html';const back=new URL(from,location.href);if(/^[0-9A-Z]{6}$/.test(q.get('code')||''))back.searchParams.set('code',q.get('code'));document.getElementById('terms-back').href=back.href;
 if(matchMedia('(max-width:760px)').matches)document.body.classList.add('mobile');
 const analysis=document.getElementById('terms-analysis-tabs');for(const [id,label] of [['dist','분배'],['perf','실제성과'],['capital','원금체력'],['mdd','MDD·회복'],['market','시장대비'],['facts','팩트']]){const a=document.createElement('a'),url=new URL(back);url.hash=id;a.className='analysis-tab';a.href=url.href;a.textContent=label;analysis.append(a);}const current=document.createElement('a');current.className='section-terms analysis-tab active';current.href=location.href;current.textContent='용어';current.setAttribute('aria-current','page');analysis.append(current);
 for(const [id,item] of Object.entries(data.terms)){const link=document.createElement('a');link.href='#'+id;link.textContent=item.title;nav.append(link);const section=document.createElement('section');section.id=id;const heading=document.createElement('h2');heading.textContent=item.title;section.append(heading);for(const block of item.detail_blocks||[]){if(!block.text&&!block.bullets?.length)continue;if(block.heading){const h=document.createElement('h3');h.textContent=block.heading;section.append(h);}if(block.text){const p=document.createElement('p');p.className='term-detail-copy';copyText(p,block.text);section.append(p);}if(block.bullets?.length){const ul=document.createElement('ul');ul.className='term-detail-copy';for(const text of block.bullets){const li=document.createElement('li');copyText(li,text);ul.append(li);}section.append(ul);}}sections.append(section);}
 // The sections are data-driven, so apply an incoming anchor after insertion.
 const target=document.getElementById(decodeURIComponent(location.hash.slice(1)));if(target)target.scrollIntoView();
})();
